# Generated by Django 5.2.7 on 2025-10-22 03:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('total_disputes', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_completion_time', models.FloatField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('trust_health', models.FloatField(default=0)),
                ('ai_confidence', models.FloatField(default=0)),
                ('system_load', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrendForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g., weekly, monthly', max_length=50)),
                ('metric', models.CharField(help_text='e.g., revenue, disputes, signups', max_length=50)),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('ongoing_projects', models.PositiveIntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_project_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.FloatField(default=0)),
                ('dispute_rate', models.FloatField(default=0)),
                ('on_time_delivery', models.FloatField(default=0)),
                ('recommendation_score', models.FloatField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('growth_index', models.FloatField(default=0)),
                ('trust_index', models.FloatField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('notifications_read', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
