# Generated by Django 5.2.7 on 2025-10-22 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('skill', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_score', models.FloatField(default=0)),
                ('competition_score', models.FloatField(default=0)),
                ('success_probability', models.FloatField(default=0)),
                ('avg_bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_hire_time', models.FloatField(default=0)),
                ('trend_direction', models.CharField(default='stable', max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
