# Generated by Django 5.2.7 on 2025-10-27 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'zip', 'docx'])]),
        ),
    ]
