# Generated by Django 5.2.7 on 2025-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
