# Generated by Django 5.2.7 on 2025-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_passed_basic_english_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_passed_category_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_video_intro',
            field=models.BooleanField(default=False),
        ),
    ]
