# Generated by Django 5.2.7 on 2025-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='has_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='test_reference',
            field=models.UUIDField(blank=True, help_text='Reference ID for associated test', null=True),
        ),
    ]
