# Generated by Django 5.2.7 on 2025-11-08 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_subcategory_has_test_subcategory_test_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('english', 'Basic English'), ('skill', 'Skill Based')], max_length=50)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=60)),
                ('weight', models.FloatField(default=5.0)),
                ('time_limit_sec', models.PositiveIntegerField(default=1200)),
                ('randomize', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='categories.skill')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text="{'A':'...','B':'...','C':'...','D':'...'}")),
                ('correct_answer', models.CharField(max_length=5)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assesments.test')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('invalid', 'Invalid')], default='started', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('percent_cached', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assesments.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.CharField(max_length=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assesments.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['type', 'active'], name='assesments__type_97f842_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'test'], name='assesments__user_id_392d69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('user', 'test', 'attempt_no')},
        ),
    ]
