# Generated by Django 5.2.7 on 2025-10-20 11:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=list, help_text='List of {user_id, score, reason}')),
                ('source', models.CharField(default='heuristic', max_length=50)),
                ('ttl_seconds', models.IntegerField(default=3600)),
            ],
            options={
                'indexes': [models.Index(fields=['project_id', 'computed_at'], name='recommendat_project_0d28b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=list, help_text='List of {project_id, score, reason}')),
                ('source', models.CharField(default='heuristic', max_length=50)),
                ('ttl_seconds', models.IntegerField(default=3600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'computed_at'], name='recommendat_user_id_a5bd43_idx')],
            },
        ),
    ]
